import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import fuel from '@fuel-js/wallet';
import { useEffect, useRef, useState } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const wallet = useRef<fuel.Wallet | null>(null);
  const [balance, setBalance] = useState(0);

  const connect = async () => {
    // @ts-ignore
    await window.ethereum.enable();
  }

  const deposit = async () => {
    // @ts-ignore
    const wallet = new fuel.Wallet(window.ethereum, {});
    await wallet.deposit('0x0000000000000000000000000000000000000000', fuel.utils.parseEther('0.0001'));
  }

  const updateBalance = async () => {
    // @ts-ignore
    const wallet = new fuel.Wallet(window.ethereum, {});
    const bal = await wallet.balance('0x0000000000000000000000000000000000000000');
    setBalance(bal);
  }

  useEffect(() => {
    updateBalance();
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
        </div>

        <div className={styles.center}>
          <div>
            <button onClick={connect}>Connect</button>
            <button onClick={deposit}>Deposit</button>
          </div>
          <div>{fuel.utils.formatEther(balance, 'ether')}</div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
